/**
 * Autogenerated by Thrift Compiler (0.9.0)
 * 
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * 
 * @generated
 */
package org.waarp.thrift.r66;

public enum Action implements org.apache.thrift.TEnum {
    Exist(1),
    Cancel(2),
    Stop(3),
    Restart(4),
    Detail(10),
    List(11),
    Mlsx(12);

    private final int value;

    private Action(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * 
     * @return null if the value is not found.
     */
    public static Action findByValue(int value) {
        switch (value) {
            case 1:
                return Exist;
            case 2:
                return Cancel;
            case 3:
                return Stop;
            case 4:
                return Restart;
            case 10:
                return Detail;
            case 11:
                return List;
            case 12:
                return Mlsx;
            default:
                return null;
        }
    }
}
