DROP INDEX idx_config;
DROP INDEX idx_hostconf;
DROP INDEX idx_host;
DROP INDEX idx_rule;
DROP INDEX idx_run_filter;
DROP SEQUENCE runseq;
DROP TABLE configuration PURGE;
DROP TABLE hostconfig PURGE;
DROP TABLE hosts PURGE;
DROP TABLE multiplemonitor PURGE;
DROP TABLE rules PURGE;
DROP TABLE runner PURGE;
